# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: puyuan
# spec:
#   # The selector matches the ingress gateway pod labels.
#   # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
#   selector:
#     istio: ingressgateway
#   servers:
#   - port:
#       number: 80
#       name: http
#       protocol: HTTP
#     hosts:
#     - "*"
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: puyuan
# spec:
#   hosts:
#   - "*"
#   gateways:
#   - puyuan
#   http:
#   - route:
#     - destination:
#         host: puyuan
#         subset: v1
#         port:
#           number: 100
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: DestinationRule
# metadata:
#   name: puyuan
# spec:
#   host: puyuan
#   subsets:
#   - name: v1
#     labels:
#       version: v1
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: puyuan
spec:
  hosts:
    - puyuan
  http:
  - route:
    - destination:
        host: puyuan
        subset: v1
      weight: 100
    mirror:
      host: puyuan
      subset: v2
    mirrorPercentage:
      value: 100.0
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: puyuan
spec:
  host: puyuan
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2