apiVersion: v1
kind: Pod
metadata:
  name: timeseries
  labels:
    sidecar.istio.io/inject: "false"
spec:
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: local-pvc
  containers:
  - name: timeseries
    image: timeseries
    imagePullPolicy: Never
    # command: ["/bin/bash"]
    # args: ["-c", "python3 atb_vpa.py"]
    command:
      - "sleep"
      - "604800"
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-data