apiVersion: v1
kind: Pod
metadata:
  name: all-vpa
  labels:
    sidecar.istio.io/inject: "false"
spec:
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: local-pvc
  containers:
  - name: atbvpa
    image: atbvpa
    imagePullPolicy: Never
    # command: ["/bin/bash"]
    # args: ["-c", "python3 atb_vpa.py"]
    command:
      - "sleep"
      - "604800"
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-data
  # - name: getpro
  #   image: getpro
  #   imagePullPolicy: Never
  #   command: ["/bin/bash"]
  #   args: ["-c", "python3 prometheus.py"]
  #   volumeMounts:
  #   - name: shared-volume
  #     mountPath: /shared-data
  # - name: vpaget
  #   image: vpaget
  #   imagePullPolicy: Never
  #   command:
  #     - "sleep"
  #     - "604800"

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
rules:
- apiGroups: ["*"]  
  resources: ["customobjects","namespaces","deployments","verticalpodautoscalers","pods","events" ]
  verbs: ["get","list","create","watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pods-list
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: pods-list
  apiGroup: rbac.authorization.k8s.io
