apiVersion: apps/v1
kind: Deployment
metadata:
  name: puyuan-v2
  labels:
    auto_build_vpa: ye
spec:
  replicas: 2
  selector:
    matchLabels:
      app: puyuan
      version: v2
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        app: puyuan
        version: v2
    spec:
      containers:
      - name: puyuan
        image: pu
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 99m
            memory: 5Mi
        command: ["python3","manage.py","runserver","0.0.0.0:80","--noreload"]

