apiVersion: v1
kind: Pod
metadata:
  name: cloneyaml
spec:
  containers:
  - name: cloneyaml
    image: cloneyaml
    imagePullPolicy: Never
    command: ["python3"]
    args: ["send_to_host.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: cloneyaml-s
spec:
  selector:
    app: cloneyaml
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080
  clusterIP: 10.101.95.110
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-d
rules:
- apiGroups: ["*"]
  resources: ["deployment"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-d
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: create-d
  apiGroup: rbac.authorization.k8s.io