apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mys
spec:
  scaleTargetRef:
    name: puyuan-v1
  minReplicaCount: 2   
  maxReplicaCount: 10
  pollingInterval: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.pro.svc.cluster.local:9090
      metricName: django_http_requests_total_by_method_total
      threshold: '20'
      query: avg(rate(django_http_requests_total_by_method_total{method="POST"}[30s]))

#curl -G --data-urlencode "query=avg(rate(django_http_requests_total_by_method_total{method=\"POST\"}[30s]))" 
#"http://prometheus-kube-prometheus-prometheus.pro.svc.cluster.local:9090/api/v1/query"