apiVersion: apps/v1
kind: Deployment
metadata:
  name: puyuan-v1
  labels:
    auto_build_vpa: ye
spec:
  replicas: 2
  selector:
    matchLabels:
      app: puyuan
      version: v1
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        auto_build_vpa: ye
        app: puyuan
        version: v1
    spec:
      containers:
      - name: puyuan
        image: pu
        imagePullPolicy: IfNotPresent
        resources:
          limit:
            cpu: 100m
            memory: 50Mi
        command: ["python3","manage.py","runserver","0.0.0.0:80","--noreload"]

