apiVersion: v1
kind: Pod
metadata:
  name: canary
  labels:
    sidecar.istio.io/inject: "false"
spec:
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: local-pvc
  containers:
  - name: canary
    image: canary
    imagePullPolicy: Never
    # command: ["/bin/bash"]
    # args: ["-c", "python3 canary.py"]
    command:
      - "sleep"
      - "604800"
    volumeMounts:
    - name: shared-volume
      mountPath: /shared-data
---
apiVersion: v1
kind: Service
metadata:
  name: canary
  labels:
    app: canary
spec:
  type: NodePort
  selector:
    app: canary
  ports:
    - protocol: TCP
      port: 80
      nodePort: 31314
---
